swagger: "2.0"
info:
  title: Argent Bank API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "201":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "201":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "201":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction/{currentMonth}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User Current Month All Transaction API
      description: Api for fetching all transaction in current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: currentMonth
          required: true
          type: string
          minLength: 7
          description: transaction current Month
      produces:
        - application/json
      responses:
        "200":
          description: User transaction in current month retrieved successully
          schema:
            $ref: "#/definitions/UserTransactionsCurrentMonth"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction/new-transaction:
    post:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User New Transaction API
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserUniqueTransaction"
      produces:
        - application/json
      responses:
        "201":
          description: User transaction is created successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User Unique Transaction API
      description: Api for fetching one transaction by its id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          minimum: 1
          description: transaction id
      produces:
        - application/json
      responses:
        "200":
          description: User unique transaction retrieved successully
          schema:
            $ref: "#/definitions/UserUniqueTransaction"
        "400":
          description: Invalid Fields
        "403":
          description: unautorized
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User Unique Transaction API
      description: Api for updating one transaction by its id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          minimum: 1
          description: transaction id
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserUniqueTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction modified successully
          schema:
            $ref: "#/definitions/UserUniqueTransaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User Unique Transaction API
      description: Api for deleting one transaction by its id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          minimum: 1
          description: transaction id
      produces:
        - application/json
      responses:
        "200":
          description: User transaction deleted successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserTransactionsCurrentMonth:
    type: array
    items:
      type: object
      description: all transaction items
      properties:
        title:
          type: string
        id:
          type: number
          format: integer
        amount:
          type: number
          format: double
        description:
          type: string
        date:
          type: string
        note:
          type: string
        category:
          type: string
        balance:
          type: number
          format: double
  UserUniqueTransaction:
    type: object
    description: transaction unique item
    properties:
      title:
        type: string
      id:
        type: number
        format: integer
      amount:
        type: number
        format: double
      description:
        type: string
      date:
        type: string
      note:
        type: string
      category:
        type: string
      balance:
        type: number
        format: double
